CREATE TABLE `item`(
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) DEFAULT NULL,
	`price` FLOAT DEFAULT NULL,
	`createTime` DATETIME DEFAULT NULL,
	`detail` VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf-8;


INSERT INTO item VALUES ('1','电视机','4500','2020-12-30 11:30:16','小米电视');